# Generated by Django 5.0 on 2024-05-04 15:38

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('address', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('cryptonites', models.DecimalField(decimal_places=4, default=0.0, max_digits=7)),
                ('crypton', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_referred_users', models.IntegerField(default=0)),
                ('is_vendor', models.BooleanField(default=False)),
                ('bio', models.TextField(default=' ', max_length=400)),
                ('contact_link', models.URLField(blank=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wallet')),
            ],
        ),
    ]
