# Generated by Django 5.0 on 2024-05-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_profile_bio_alter_profile_contact_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miningbot',
            name='max_hp',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
